apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-microservice-forex-service-v1
  labels:
    commit: ${WERCKER_GIT_COMMIT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-microservice-forex-service
  template:
    metadata:
      labels:
        app: spring-boot-microservice-forex-service
        commit: ${WERCKER_GIT_COMMIT}
    spec:
      containers:
      - name: spring-boot-microservice-forex-service
        image: ${DOCKER_REPO}:${WERCKER_GIT_REPOSITORY}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - name: spring-boot-microservice-forex-service
          containerPort: ${PORT}
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-microservice-forex-service
  labels:
    app: spring-boot-microservice-forex-service
    commit: ${WERCKER_GIT_COMMIT}
spec:
  ports:
  - port: 30000
    targetPort: ${PORT}
  selector:
    app: spring-boot-microservice-forex-service
  type: ClusterIP
---